### ISSUE TITLE
Reveal and Highlight Matching Should Use Alternate Name

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/EndorsementExtension#26]
When scanning this endorsement page:
https://runforsomething.net/candidates/

...I used the "Reveal" button for "Tamara Sawyer". It did not find her. I did find her on the page with her alternate name highlighted "Tami Sawyer". https://api.wevoteusa.org/c/57445/edit/?google_civic_election_id=1000085&state_code=&page=0

The request is to:
1) use the alternate name for highlighting support/oppose colors
2) have the "Reveal" button use the alternate name if the full name isn't found
![Screen Shot 2019-09-27 at 5 55 18 AM](https://user-images.githubusercontent.com/7756031/65770695-70728300-e0eb-11e9-8e00-50c18f26853b.png)

**Comment by DaleMcGrew** [comment]
I think the new changes I made today (providing candidate_alternate_names in voterGuidePossibilityHighlightsRetrieve and voterGuidePossibilityPositionsRetrieve) will make fixing this issue more possible.

**Comment by SailingSteve** [comment]
Reveal in position pane, now uses alternate names.   From the suggestion pop-up does not -- this could be fixed, but would require a more complicated global fix.

Highlight matching was fixed by Dale's fix which sends more highlight aliases from the server.

**Comment by DaleMcGrew** [comment]
Verified, thank you!
