### ISSUE TITLE
Height Mismatch: Large panel and Right Panel

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/EndorsementExtension#27]
I'm enjoying working with the new endorsement chrome extension!

In order to make vertical scrolling more intuitive, please eliminate the overall window vertical and horizontal scrollbars. This will limit the vertical scrolling to either the left-most main panel, or the right "candidate-browser" panel. Example page: https://workingfamilies.org/2019/08/2019-endorsements/

Also, the right candidate-browser panel has a left-right scroll that it would be good to remove. The width of the right candidate-browser panel can be fixed. The main large panel can always be "forced down" in width by the right candidate-browser panel.

If required by the page in the main large panel, a horizontal left-right scroll is fine, if it has a fixed width.

Please test at a variety of desktop browser window sizes.

**Comment by SailingSteve** [comment]
right left is "easy"

**Comment by SailingSteve** [comment]
I'm not sure if this is a complete fix, but is seems greatly improved.

**Comment by DaleMcGrew** [comment]
This was a great iteration @SailingSteve. Closing this issue.
