### ISSUE TITLE
Panel Widths: Bugs for One Organization

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/EndorsementExtension#29]
I noticed that this website had three problems when our Endorsement Tool is turned on:
https://runforsomething.net/candidates/

1. The right panel is very wide, and the left panel is very narrow. The right panel can be a fixed with.

2. Reveal button doesn't work

3. Candidate details are expanded all the time

**Comment by SailingSteve** [comment]
4. The iframe which holds the endorsement webpage will not responsively grow once it is created.  The symptoms is a blank or colored box at the bottom of the page, after you have stretched it.

**Comment by SailingSteve** [comment]
Big improvement in 0.0.0.0.5

**Comment by SailingSteve** [comment]
Better fix in 0.0.0.6

**Comment by DaleMcGrew** [comment]
Verified!
