### ISSUE TITLE
"Not in Main Panel" Indicator Added to Right Panel

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/EndorsementExtension#30]
We would very much like to have a way to see which found items in the right column are actually not visible in the left main panel. (As quality control against false-positives.)

It could be as simple as a red dot to the right of the candidate's name if the name can't be found in the main panel.

**Comment by SailingSteve** [comment]
<img width="976" alt="Screen Shot 2019-10-03 at 9 31 02 AM" src="https://user-images.githubusercontent.com/6923653/66145980-b2ef0080-e5c0-11e9-9241-421ef558eb93.png">

**Comment by SailingSteve** [comment]
Done, coming in 0.0.0.0.6

**Comment by DaleMcGrew** [comment]
Thank you!
