### ISSUE TITLE
Broken "candidate" image

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/EndorsementExtension#33]
When I visit this URL: https://www.cleanvirginia.org/our-endorsements/
...and turn the We Vote Endorsement Tool on, I see this in the upper right corner:
![Screen Shot 2019-09-28 at 11 46 37 AM](https://user-images.githubusercontent.com/7756031/65821083-c6c3ec80-e1e5-11e9-8df1-bcfc901941a9.png)

When I right click and go to "Open Image in New Tab", I am taken to this URL:
https://www.cleanvirginia.org/our-endorsements/null

**Comment by SailingSteve** [comment]
I can't get this to reproduce.
We'll have to try again after the next version is released to the chrome store.

**Comment by DaleMcGrew** [comment]
It might be caused by using the tool when you aren't signed in? Or maybe I was signed in using an account that didn't have a photo?

**Comment by SailingSteve** [comment]
There is a new version getting approved now, 0.0.0.0.5, I did a bunch of 
work on sign in, and state notification.  Hopefully it will fix it.

**Comment by DaleMcGrew** [comment]
Fix verified.
