### ISSUE TITLE
Add Endorsement Status Icon(s) to Right Column

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/EndorsementExtension#36]
Please add these icon squares with thumbs up, thumbs down, and comment to the top right of each candidate's "rolled up" block in the right column:

Thumb Up: https://material.io/resources/icons/?icon=thumb_up&style=baseline
Thumb Down: https://material.io/resources/icons/?icon=thumb_down&style=baseline
Comment Icon: https://material.io/resources/icons/?icon=comment&style=baseline

1) Endorsed with comment (not stored/imported):
<img width="470" alt="Screen Shot 2019-10-09 at 6 00 11 PM" src="https://user-images.githubusercontent.com/7756031/66530916-b56cc100-eabe-11e9-8ee4-41e1b9d1374c.png">

2) Endorsed, no comment (not stored/imported):
<img width="393" alt="Screen Shot 2019-10-09 at 6 01 16 PM" src="https://user-images.githubusercontent.com/7756031/66530937-d03f3580-eabe-11e9-9768-a288ac4cdd44.png">

3) Endorsed with comment (stored/imported):
<img width="472" alt="Screen Shot 2019-10-09 at 6 02 11 PM" src="https://user-images.githubusercontent.com/7756031/66530982-f238b800-eabe-11e9-94e7-e78a9c78dab6.png">

4) Comment only (not stored/imported)
<img width="462" alt="Screen Shot 2019-10-09 at 6 02 53 PM" src="https://user-images.githubusercontent.com/7756031/66531015-15636780-eabf-11e9-874c-78198fe0d43b.png">

5) Comment only (Was stored/imported)
<img width="467" alt="Screen Shot 2019-10-09 at 6 03 00 PM" src="https://user-images.githubusercontent.com/7756031/66531024-1c8a7580-eabf-11e9-8896-e25e465997ad.png">

**Comment by SailingSteve** [comment]
Talked to Dale at standup:
The stance data can be used for this, as when displaying the  unfurled state.
The other state  boolean `not (stored or imported)` or `stored and imported` is based on the existence of a position_we_vote_id value

```
{possibility_position_id: 31259, possibility_position_number: 1,…}
ballot_item_name: "Cottie Petrie-Norris"
candidate_alternate_names: []
candidate_twitter_handle: ""
candidate_we_vote_id: ""
google_civic_election_id: null
measure_we_vote_id: null
more_info_url: "https://www.emilyslist.org/pages/entry/state-and-local-candidates"
organization_name: "Emily's List"
organization_twitter_handle: "emilyslist"
organization_we_vote_id: "wv02org105"
position_should_be_removed: false
position_stance: "SUPPORT"
position_we_vote_id: null
possibility_position_id: 31259
possibility_position_number: 1
possibility_should_be_deleted: false
possibility_should_be_ignored: false
state_code: ""
statement_text: "	CA-AD74"
'''

**Comment by DaleMcGrew** [comment]
Verified.
