### ISSUE TITLE
Right column text edits

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/EndorsementExtension#39]
1)
Please change the text on the "Web App" button to say "WeVote.US".

2)
Edit down this text to fit on one line:
"If a more detailed endorsement exists, enter its URL here:"
Suggested: 
"If dedicated candidate page exists, enter URL here:"

3)
Reduce font size of URL in the "If a more detailed endorsement exists, enter its URL here:" input box so we can see more of it in the space available.

**Comment by SailingSteve** [comment]
Sub issues
1) Done 9/11/18, in 0.0.0.6
2) Done 9/11/18, in 0.0.0.6
3) Not yet worked on.

**Comment by DaleMcGrew** [comment]
Fix verified.
