### ISSUE TITLE
Icon for Dark Mode

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/EndorsementExtension#42]
I use dark mode for my computer. This is how our Chrome extension icon looks in dark mode next to the other logos -- it should have the white background:
![Screen Shot 2019-10-11 at 11 48 23 AM](https://user-images.githubusercontent.com/7756031/66676748-0c88a800-ec1d-11e9-8b4d-023668bc0fae.png)

**Comment by SailingSteve** [comment]
@DaleMcGrew  How do you turn on dark mode?  Do you use a chrome plug in?

**Comment by DaleMcGrew** [comment]
On the Mac: System Settings > General > Appearance > Dark
