### ISSUE TITLE
Add a pop-up menu for the 'W' extension icon after a Left Click

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/EndorsementExtension#48]
Add a menu that pops down when you click on the We Vote Chrome Extension icon:
![Screen Shot 2019-12-19 at 4 21 54 PM](https://user-images.githubusercontent.com/7756031/71220039-fe3db480-227b-11ea-9684-1355c1d5681b.png)

- [x] "Jump To My Ballot" button should open a new tab and go to: https://WeVote.US/ballot
- [ ] "All Endorsements: Sierra Club" should open a new tab and go to: https://WeVote.US/sierraclub/positions
- [ ] The "View Candidates" on/off switch would cause candidates we recognize to be highlighted on any page (for all Chrome tabs) that isn't in the "ignore these websites" list
 - [x] The "Open Edit Panel" would be the same as the current "Turn on the Extension" behavior that happens when you click the We Vote Chrome Extension icon. We would like to only turn on the Edit panel in the tab that is currently open, and *not* turn on the Edit panel in any other tabs.

Note: the existing We Vote Chrome Extension icon itself does not need to be changed -- it is fine as is:
![Screen Shot 2019-12-19 at 4 23 50 PM](https://user-images.githubusercontent.com/7756031/71220035-f9790080-227b-11ea-8b70-c83ccdc5b98a.png)

Note the We Vote logo for the top of this popdown menu can be found here:
https://wevote.us/img/we-vote-logo-horizontal-color-dark-141x46.svg

**Comment by SailingSteve** [comment]
@DaleMcGrew 
Does _"All Endorsements: Sierra Club" should open a new tab and go to: https://WeVote.US/sierraclub/positions_ appear, because you are on https://www.sierraclub.org/  ?
what if you are on https://www.sierraclub.org/west-virginia?

**Comment by DaleMcGrew** [comment]
It is the voter guide page on the web app for whichever organization is associated with that endorsement page. (That is, the organization that we choose as the speaker on that page, using the voter guide possibility tool.)

**Comment by SailingSteve** [comment]
Caveats re:  "All Endorsements: Sierra Club" should open a new tab and go to: https://WeVote.US/sierraclub/positions

If the user is not logged in, or is never logged in, and the exact URL for the endorsement page does not map to one of our records, this button will have to be grayed out

**Comment by SailingSteve** [comment]
<img width="501" alt="Screen Shot 2020-02-11 at 1 26 05 PM" src="https://user-images.githubusercontent.com/6923653/74280840-2a9d0c80-4cd2-11ea-99f3-171e3f6e8b4b.png">


I implemented this in a different way than the mock. I really believe we need to have more fine-grained control over which pages have highlighting going on them.  Dale really wants them to be "all on", but my feeling is that until other people get a feel for what the load is, the cost of having highlighting "on all" is hard to appreciate. I had the UI exactly as in the mock but it quickly showed as difficult to use. So this is the way it is for now.
