### ISSUE TITLE
Add Icons to Highlighted Names

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/EndorsementExtension#49]
Add icons to all of these states. Change yellow "candidate found"/"name recognized but no endorsement" color to dark gray.
![Screen Shot 2019-12-19 at 5 51 00 PM](https://user-images.githubusercontent.com/7756031/71223234-26cbab80-2288-11ea-9dba-855218387111.png)

**Comment by SailingSteve** [comment]
This is code complete, and will be in the next pull request
