### ISSUE TITLE
Candidate highlighted (Green/Red), signed in: Sierra Club Endorsement

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/EndorsementExtension#59]
This would also be the default tab to show if in the Edit Panel mode:

![Screen Shot 2020-02-28 at 11 06 28 AM](https://user-images.githubusercontent.com/7756031/75579313-634f1c80-5a1a-11ea-9b77-5d5d168b0d1d.png)

**Comment by SailingSteve** [comment]
This has been moved to the WebApp, and Jarred is working on it.
