### ISSUE TITLE
Edit Panel, Sign In Process

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/EndorsementExtension#60]
![Screen Shot 2020-02-28 at 11 12 09 AM](https://user-images.githubusercontent.com/7756031/75579688-3b13ed80-5a1b-11ea-9724-227b331adb65.png)

Clicking "Sign in" would open a new tab to WeVote.US as explained in this Issue in the WebApp Issues list:
https://github.com/wevote/WebApp/issues/2819

**Comment by SailingSteve** [comment]
Done
