### ISSUE TITLE
Update highlight colors

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/EndorsementExtension#61]
![Screen Shot 2020-02-28 at 11 38 08 AM](https://user-images.githubusercontent.com/7756031/75581665-d22e7480-5a1e-11ea-8038-34c482c86931.png)

**Comment by SailingSteve** [comment]
Mostly done, I'd like to hold off on the "Name Recognized but no endorsement" color change, since the yellow highlight color is so visible, it help me test.

**Comment by SailingSteve** [comment]
These have mostly been removed, to handle a simplified extension based on the V3 api.  They could be revived.
